name: Java CI with Gradle

on:
  push:
    branches: [ "feature/**" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./YouToy

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: working directory check
      run: pwd
      working-directory: ${{ env.working-directory }}
    - name: check files
      run: ls
      working-directory: ${{ env.working-directory }}
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ${{ env.working-directory }}
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{ env.working-directory }}
    - name: Test with Gradle
      run: ./gradlew :test --tests com.pellto.youtoy.*
      working-directory: ${{ env.working-directory }}
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: ${{ always() }}
      with:
        files: /home/runner/work/YouToy/YouToy/YouToy/build/test-results/**/*.xml
